### PR TITLE
fix: allow `openDBI` within write transaction

### LINKED ISSUE #13: Open a collection inside a write transaction
I'm getting this error:
```
MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag
```

Is there a workaround for this?

### PR DESCRIPTION
**Pull request by aleclarson**
Fixes #13

### CODE REVIEW

File: nimdbx/Database.nim [hunk 1]
```diff
@@ -12,6 +12,7 @@ type
     DatabaseObj* = object
         m_env {.requiresInit.}: ptr MDBX_env
         m_collections: Table[string, ref RootObj]
+        m_txn: ptr MDBX_txn
```
Comment (aleclarson) [inline nimdbx/Database.nim:15]: The current transaction from `beginTransaction` is cached here, so it can be accessed in `openDBI`. This allows for the creation of collections from within a transaction.

File: nimdbx/Transaction.nim [hunk 2]
```diff
@@ -100,6 +101,7 @@ proc commit*(t: Transaction) =
     ## finished.
     check mdbx_txn_commit(t.i_txn)
     t.m_txn = nil
+    t.database.i_txn = nil
```
Comment (aleclarson) [inline nimdbx/Transaction.nim:104]: The transaction is released on `commit` or `abort`.

**Comment by snej** [comment]
Thanks! Sorry it took me so long to see this PR...

**Comment by aleclarson** [comment]
Glad you got around to it 🎉
